modLoader="javafml" #mandatory
loaderVersion="[32,)"
# TODO decide whether I want MIT or something else
license="MIT"
[[mods]]
modId = "controlengineering"
# TODO
version = "0.0"
displayName = "Control Engineering"
authors = "malte0811"
description = '''
An addon for Immersive Engineering providing control panels and "logic boxes"
'''
[[dependencies.controlengineering]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.controlengineering]]
modId = "immersiveengineering"
mandatory = true
versionRange = "[1.17.1-5.0.2,)"
ordering = "AFTER"
side = "BOTH"
