modLoader="javafml" #mandatory
loaderVersion="[32,)"
license="MIT"
[[mods]]
modId = "controlengineering"
version = "${ce_version}"
displayName = "Control Engineering"
authors = "malte0811"
logoFile = "logo.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/control-engineering"
description = '''
An addon for Immersive Engineering providing control panels and logic cabinets among other related devices
'''
[[dependencies.controlengineering]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.controlengineering]]
modId = "immersiveengineering"
mandatory = true
versionRange = "[${ie_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.controlengineering]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
side = "BOTH"
