modLoader="javafml" #mandatory
loaderVersion="[32,)"
# TODO decide whether I want MIT or something else
license="MIT"
[[mods]]
modId="controlengineering"
# TODO
version="v"
displayName="Control Engineering"
authors="malte0811"
description='''
An addon for Immersive Engineering providing control panels and "logic boxes"
'''
[[dependencies.controlengineering]]
    modId="immersiveengineering"
    mandatory=true
    versionRange="[0.16,)"
    ordering="AFTER"
    side="BOTH"
