name: Run tests and datagen, and publish artifacts

on:
  push:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Run unit tests
        run: ./gradlew test
      - name: Create list of existing generated resources
        run: find src/generated/resources/ ! -path "**/.cache*" > resources.txt
      - name: Run data generation
        run: ./gradlew runData
      - name: Check that no files have changed
        # TODO --exit-code doesn't seem to be working as advertised?
        run: git update-index --really-refresh && git diff-index --ignore-all-space HEAD && git diff-index --ignore-all-space --quiet HEAD || (git diff && false)
      - name: Create list of actual generated resources
        run: find src/generated/resources/ ! -path "**/.cache*" > resources_new.txt
      - name: Check that no new resources have been created
        run: diff resources.txt resources_new.txt
      - name: Build CE
        run: ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/libs/*.jar
